version: "3.9"

services:
  repo:
    image: postgres:15.1-alpine3.17
    restart: always
    container_name: mylib_repo
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - repo_data:/var/lib/postgresql/data
    networks:
      - mylib
  api:
    build: .
    container_name: mylib_rest_api
    privileged: true
    ports:
      - ${SRV_PORT}:${SRV_PORT}
    depends_on:
      - repo
    networks:
      - mylib

volumes:
  repo_data:

networks:
  mylib:
    driver: bridge